# Generated by Django 5.2.8 on 2026-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_brand_logo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_image_per_color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='view_type',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side'), ('other', 'Other')], default='front', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'view_type'), name='unique_image_per_color_view'),
        ),
    ]
