# Generated by Django 5.2.8 on 2026-02-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productimage_unique_image_per_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='store.product')),
            ],
            options={
                'unique_together': {('product', 'color')},
            },
        ),
    ]
