# Generated by Django 5.2.8 on 2026-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_colorstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=10),
        ),
    ]
